### PR TITLE
Add the ability to set a custom adapter by config

### LINKED ISSUE #9: TODO Rework AdapterFactory so it can modify the adapter_map on runtime from configuration
see https://github.com/bushbaby/BsbFlysystem/issues/4#issuecomment-96522829

- [ ] rework factory to allow runtime adapter_map
- [ ] remove constructor as it becomes useless
- [ ] tweak unittest
- [ ] documentation

### PR DESCRIPTION
**Pull request by iam-merlin**
resolve #9 , after tests review, it was not necessary to add more tests and a simple update was enough.

### CODE REVIEW

**Comment by iam-merlin** [comment]
for reference ("Rogntudjuuuu")
 Rogntudjuuuu

**Comment by iam-merlin** [comment]
@basz I let you review, don't know why Scrutinizer is failing seems travis was too long to build/test :(

**Comment by basz** [comment]
Travis had some issues due to an update which they rolled back.

I think it looks fine - I just have a fever today and in bed :-/ I'll see if I'll merge today. 

Did you find any other improvement to be made?

**Comment by iam-merlin** [comment]
Hi,
Take care ;)

For improvements :

- In documentation, this can be interesting to explain how to create **Bsb** adapter that is only supported in a zf2 project and how to port to zf2 a custom flysystem adapter.( It needs a lot of work and for that, I don't have enough time.)
- The list of adapter should not be here (more exactly should contains only league default flysystem adapter). Maybe a specific repository will be better? (In the other hand... it's cool work and the project is too small to be split.)

It's poor but I've got no more ideas for now. If you have some, don't hesitate to share ^^.

**Comment by basz** [comment]
it's been merged and released as 1.2.0. Thanks a lot for your contribution!

**Pull request merged**
