### PR TITLE
Only require required packages

### PR DESCRIPTION
**Pull request by jaapio**
not all zend framework components are required by this package. To keep this package leaner it is better to just install the required packages

### CODE REVIEW

**Comment by basz** [comment]
you are right - thans for the contribution

tip! use this to (help) find dependancies : grep -Rh 'use Zend\\' ./src | sort | uniq

If you would please add these to require-dev so the tests will complete

```
    "require-dev": {
        ...,
        "zendframework/zend-config": "~2.2",
        "zendframework/zend-i18n": "~2.2",
        "zendframework/zend-loader": "~2.2",
        "zendframework/zend-log": "~2.2",
        "zendframework/zend-mvc": "~2.2",
        "zendframework/zend-view": "~2.2"
    },
```

**Comment by jaapio** [comment]
updated it.

**Comment by jaapio** [comment]
excuse me, missed that. Updated, and removed the previous commit

**Comment by basz** [comment]
meh....

"Pull Requests that have a failing status can’t be merged from a phone."

"Bit but but, it's an eyePhone.. It sees •everything•..."

**Pull request merged**
