### PR TITLE
[REMOVE] zend service manager from factories

### PR DESCRIPTION
**Pull request by Orkin**
Update interface to PsrContainerInterface to allow to use any other service manager who implement the PSR 11

### CODE REVIEW

**Comment by basz** [comment]
Nice. I’ll make those tests pass as it is an issue with my code styling lib.

**Comment by Orkin** [comment]
Yes, I think you can upgrade some minimal dependencies versions and it could be great to remove the use of PluginManager (it work like that but we can’t remove the dependecy with the zend-servicemanager). As expressive allow many of containers 😊

**Comment by basz** [comment]
Thinking. Not sure if I want to remove that dependency as I use https://github.com/bushbaby/BsbFlysystem/blob/master/README.md#advanced-usage in my applications...

**Comment by Orkin** [comment]
@basz ok and what about just enabling this feature only with containers that's support it ? And make Zend ServiceManager as suggested dependencies like other container ?

I think it can be good to make this package interoperable.

I saw that de Symfony DI support also the shared option : https://symfony.com/doc/current/service_container/shared.html

**Comment by basz** [comment]
Hi, made some progress with my PR against this one. Tests are successful. I dropped support for php70 and am considering to drop php71 as well. But then I thought it's nicer to involve you in such a decision. Overall I don't use either of those versions so I'm am ok with a major release drop support for those versions. How about you?

**Pull request merged**
