### PR TITLE
Fix cs

### LINKED ISSUE #53: zendframework/zend-cache as optional dependency?
Looks like `zendframework/zend-cache` is used in some case where you need already require it. I think this library can be required as suggested and dev dependecy.

@basz what are you think?

### PR DESCRIPTION
**Pull request by snapshotpl**
* Styles
* Fixed CI for php 7.3 and 8.0
* laminas/cache is now optional Resolves #53

### CODE REVIEW

**Review by basz — APPROVED** [review]
Hi. Looks good to me. Thanks so much!

Could you please give a short run down of the changes. I'll then merge and release.

Styling
Optional Cache
Removed bushbaby/style repo
Php 8 in tests
More?

I don believe this would need a major upgrade does it?

**Comment by snapshotpl** [comment]
Description updated. Making laminas-cache optional makes little BC, but IMO it's minor because users should declare usage of laminas-cache in own composer.json. Your decision ;)

In next PR I would like to enable support for flysystem v2

**Comment by basz** [comment]
That sounds reasonable.

We could just release this pr along with support for V2.

**Comment by snapshotpl** [comment]
After initial develop with v2 I think we need to release this changes. Support for v2 will break a lot.

**Pull request merged**
