### PR TITLE
Test laminas cache in php8

### LINKED ISSUE #72: Enable testing with laminas-cache
Laminas-cache v2.10+ laminas-cache changed its dependencies on cache adapters. They are all loaded by default and a developer should disallow ones that are not needed.

This is fine, but for php 8 the APC adapter does not work. So in our tests we should not specify to not load that adapter.

Should be _replaced_ in composer.json.

```
"replace": {
    "laminas/laminas-cache-storage-adapter-apc": "*",
```

see https://github.com/laminas/laminas-cache/#avoid-unused-cache-adapters-are-being-installed

We can then enable $LAMINAS_CACHE in our tests for PHP 8 I believe

### PR DESCRIPTION
**Pull request by basz**
attempting to fix #72

### CODE REVIEW

**Comment by basz** [comment]
ping @snapshotpl

**Comment by snapshotpl** [comment]
Great!

**Review by snapshotpl — APPROVED** [review]

**Comment by snapshotpl** [comment]
@basz can you release current changes?

**Comment by basz** [comment]
I have put it on my todo for tomorrow

**Pull request merged**
