### PR TITLE
Add custom s3 endpoint for other s3 compatible hosts

### PR DESCRIPTION
**Pull request by worthwhileindustries**
Updated config dist file with config option and added the config code to adapter. Tested against minio.

### CODE REVIEW

**Comment by worthwhileindustries** [comment]
@basz hello, there seems to be some fails that are unrelated to my code change. Am I missing something?

**Comment by worthwhileindustries** [comment]
@basz bump?

**Comment by basz** [comment]
There seem to be some code style issues. Could you fix those and Ping me again? 

One problem was found in untouched code so i guess phpcsfixer got more strict.

Ps. Sorry for the delay ive been extremely the last couple of weeks.

**Comment by worthwhileindustries** [comment]
@basz ah that's my bad I thought that was library code seeing it as Zend stuff I missed that. Yeah I can fix it.

**Comment by worthwhileindustries** [comment]
@basz ok it looks done to me

**Comment by basz** [comment]
Thanks! I’ll do a proper release at a later time

**Pull request merged**
